name: Install Base

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          PACKAGE_PATH: './${{inputs.name}}/package-lock.json'
        with:
          path: ${{ inputs.name }}/node_modules
          key: ${{ inputs.name }}-cache-node-modules-${{ hashFiles(env.PACKAGE_PATH) }}
      - name: Install
        if: steps.npm_cache.outputs.cache-hit != 'true'
        working-directory: ./${{ inputs.name }}
        run: npm ci
